/**
 * Phase 0 parity safety net for merging Column_Design_DW (Python, ACI 318-19
 * column engine, calibrated against S-Concrete) into this TS app.
 *
 * The fixture `fixtures/columnParity.json` is generated by the Python reference
 * engine (Column_Design_DW/parity/export_parity_vectors.py). This test runs the
 * current TS `designColumnACI` over the same inputs and pins how closely it
 * reproduces the reference, so the upcoming engine port (Phase 1) has an
 * objective target and can't silently regress.
 *
 * What this test asserts today:
 *  - AXIAL capacity (φPn,max) and DCR_axial: TIGHT — both engines share the same
 *    ACI §22.4.2 formula, so they must agree to rounding.
 *  - P-M interaction: DOCUMENTED GAP — the TS engine uses the Bresler reciprocal
 *    method; the Python reference uses a rotating-neutral-axis solver. They agree
 *    on pass/fail and on magnitude within PM_ABS_TOL. Phase 1 ports the
 *    rotating-NA solver and should drive PM_ABS_TOL down toward ~0.03.
 *  - Shear: INFORMATIONAL — TS uses a single Vu/d=0.8h check; Python does a
 *    per-direction co-occurring-axial check. We only assert the verdicts agree.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { designColumnACI } from '../aciColumn';
import type { SectionDimensions, MaterialProps, RebarLayout, LoadCase } from '../../../types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const fixture: any = JSON.parse(
  readFileSync(new URL('./fixtures/columnParity.json', import.meta.url), 'utf-8'),
);

const barNum = (s: string): number => parseInt(String(s).replace('#', ''), 10);
const relErr = (a: number, b: number): number => Math.abs(a - b) / Math.max(Math.abs(b), 1e-9);
const round = (x: number, nd = 3): number => Number(x.toFixed(nd));

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildSection(inp: any): SectionDimensions {
  const isCirc = inp.shape === 'circular';
  return {
    type: isCirc ? 'circular_column' : 'rectangular_column',
    b: inp.b,
    h: inp.h,
    ...(isCirc ? { diameter: inp.b } : {}),
    coverClear: inp.cover,
    stirrupDia: barNum(inp.tie_bar),
  } as SectionDimensions;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildMaterial(inp: any): MaterialProps {
  return {
    fc: inp.fc_ksi * 1000,
    fy: inp.fy_ksi * 1000,
    fyt: inp.fys_ksi * 1000,
    Es: 29_000_000,
    lambdaConcrete: 1.0,
  };
}

/**
 * Map the Python per-face bar counts (nz/ny incl. corners) onto the TS
 * RebarLayout. Total Ast is preserved exactly:
 *   rect:  topBars = botBars = ny ;  sideBars = 2·(nz−2)
 *          → 2·ny + 2·(nz−2) = 2·(nz+ny) − 4 = n_bars_total ✓
 *   circ:  all bars pooled on the ring.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildRebar(inp: any): RebarLayout {
  const size = barNum(inp.long_bar);
  const ties = { barSize: barNum(inp.tie_bar), spacing: inp.s_actual, legs: 2 };
  if (inp.shape === 'circular') {
    return { topBars: [{ numBars: inp.nz, barSize: size }], botBars: [], ties, tieType: 'spiral' };
  }
  const sideCount = 2 * (inp.nz - 2);
  return {
    topBars: [{ numBars: inp.ny, barSize: size }],
    botBars: [{ numBars: inp.ny, barSize: size }],
    sideBars: sideCount > 0 ? [{ numBars: sideCount, barSize: size }] : [],
    ties,
    tieType: 'tied',
  };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function buildLoads(inp: any): LoadCase[] {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return inp.forces.map((f: any, i: number) => ({
    id: `LC${i}`,
    label: `LC${i}`,
    Mu_pos: 0,
    Mu_neg: 0,
    Vu: Math.max(Math.abs(f.V2 ?? 0), Math.abs(f.V3 ?? 0)),
    Tu: Math.abs(f.T ?? 0),
    Pu: -(f.P ?? 0), // TS convention: + compression; Python P negative = compression
    Mux: Math.abs(f.M3 ?? 0), // strong-axis moment
    Muy: Math.abs(f.M2 ?? 0), // weak-axis moment
  }));
}

/** Governing (envelope) TS outputs across all load combos for a case. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function tsGoverning(inp: any) {
  const section = buildSection(inp);
  const material = buildMaterial(inp);
  const rebar = buildRebar(inp);
  let phiPnMax = 0, dcrAxial = 0, dcrPM = 0, dcrShear = 0;
  for (const load of buildLoads(inp)) {
    const r = designColumnACI(section, material, rebar, load);
    phiPnMax = Math.max(phiPnMax, r.phi_Pn_max ?? 0);
    dcrAxial = Math.max(dcrAxial, r.DCR_axial ?? 0);
    dcrPM = Math.max(dcrPM, r.DCR_PM ?? 0);
    dcrShear = Math.max(dcrShear, r.DCR_shear ?? 0);
  }
  return { phiPnMax, dcrAxial, dcrPM, dcrShear };
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const rows = (fixture.cases as any[]).map((c) => ({
  id: c.id,
  tie: c.inputs.tie_type as string,
  ref: c.python,
  ts: tsGoverning(c.inputs),
}));

describe('column parity vectors (Phase 0)', () => {
  it('fixture loaded with the expected cases', () => {
    expect(fixture.schema).toBe('column-parity/v1');
    expect(rows.length).toBe(10);
  });

  it('reports TS-vs-Python deltas (see console output)', () => {
    const table = rows.map((r) => ({
      id: r.id,
      phiPn_ref: round(r.ref.phi_pn_kips, 1),
      phiPn_ts: round(r.ts.phiPnMax, 1),
      axial_ref: r.ref.flexural.axial_comp_util,
      axial_ts: round(r.ts.dcrAxial),
      NM_ref: r.ref.flexural.NM_util,
      PMverdict_ts: round(Math.max(r.ts.dcrPM, r.ts.dcrAxial)),
      shear_ref: r.ref.shear.VT_util,
      shear_ts: round(r.ts.dcrShear),
    }));
    // eslint-disable-next-line no-console
    console.table(table);
    expect(rows.length).toBeGreaterThan(0);
  });

  describe('axial capacity — φPn,max TIGHT (shared ACI §22.4.2 formula)', () => {
    for (const r of rows) {
      it(`${r.id}: φPn,max within 0.5% of Python`, () => {
        expect(relErr(r.ts.phiPnMax, r.ref.phi_pn_kips)).toBeLessThan(0.005);
      });
    }
  });

  describe('DCR_axial — TIGHT for tied (identical denominator)', () => {
    for (const r of rows.filter((x) => x.tie === 'tied')) {
      it(`${r.id}: DCR_axial within 0.02 of Python`, () => {
        expect(Math.abs(r.ts.dcrAxial - r.ref.flexural.axial_comp_util)).toBeLessThan(0.02);
      });
    }
  });

  describe('DCR_axial (spiral) — DOCUMENTED GAP, Phase-1 reconciliation', () => {
    // Column_Design_DW/design_engine.py:1145-1146 deliberately uses TIED φ=0.65/
    // α=0.80 for the axial-DCR denominator even on spiral columns (to match
    // S-Concrete). The TS engine uses spiral 0.75/0.85, so TS is LESS conservative
    // here. Phase 1 must adopt the S-Concrete convention to keep the calibration.
    const SPIRAL_AXIAL_TOL = 0.15;
    for (const r of rows.filter((x) => x.tie === 'spiral')) {
      it(`${r.id}: TS less conservative than Python, |Δ| < ${SPIRAL_AXIAL_TOL}`, () => {
        const ref = r.ref.flexural.axial_comp_util as number;
        expect(r.ts.dcrAxial).toBeLessThanOrEqual(ref + 1e-9);
        expect(Math.abs(r.ts.dcrAxial - ref)).toBeLessThan(SPIRAL_AXIAL_TOL);
      });
    }
  });

  describe('P-M interaction — DOCUMENTED GAP (TS Bresler vs Python rotating-NA)', () => {
    // Phase 1 ports the rotating-NA solver; tighten this toward ~0.03 then.
    const PM_ABS_TOL = 0.4;
    for (const r of rows) {
      const refUtil: number = r.ref.flexural.NM_util ?? r.ref.flexural.moment_res_util ?? 0;
      const tsUtil = Math.max(r.ts.dcrPM, r.ts.dcrAxial);
      it(`${r.id}: pass/fail verdict agrees`, () => {
        expect(refUtil >= 1).toBe(tsUtil >= 1);
      });
      it(`${r.id}: |Δutil| < ${PM_ABS_TOL} (gap to close in Phase 1)`, () => {
        expect(Math.abs(tsUtil - refUtil)).toBeLessThan(PM_ABS_TOL);
      });
    }
  });

  describe('shear — INFORMATIONAL (verdicts only; full parity is Phase 1/3)', () => {
    for (const r of rows) {
      const refShear: number = r.ref.shear.VT_util ?? 0;
      it(`${r.id}: shear pass/fail verdict agrees`, () => {
        expect(refShear >= 1).toBe(r.ts.dcrShear >= 1);
      });
    }
  });
});
